import axios from "axios";
import Head from "next/head";
import { useContext, useState } from "react";
import ProfileCard from "../components/ProfileCard";
import UserProfile from "../components/UserProfile";
import { DataContext } from "../store/GlobalState";

export default function Home(props) {
  const [contributors] = useState(props.contributors);

  const { state, dispatch } = useContext(DataContext);

  const { user, repos } = state;

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {Object.keys(user).length > 0 ? null : (
        <h1 className="text-center py-5">Top Github Contributors</h1>
      )}

      {Object.keys(user).length > 0 ? (
        <UserProfile user={user} repos={repos} />
      ) : (
        <div className="row row-cols-1 row-cols-md-2 g-4 px-3 pb-5">
          {contributors.map((profile, index) => (
            <ProfileCard key={index} profile={profile} />
          ))}
        </div>
      )}
    </div>
  );
}

export async function getServerSideProps() {
  const res = await axios.get(
    "https://api.github.com/repos/scala/scala/contributors"
  );

  return {
    props: {
      contributors: res.data,
      status: res.status,
    },
  };
}
